version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  build:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run:
          name: Construcción
          command: |
            echo "Construyendo el proyecto..."
            npm install

  test:
    docker:
      - image: cimg/node:20.5.0
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Pruebas paralelas
          command: |
            echo "Ejecutando pruebas en paralelo"
            echo "Soy el nodo $CIRCLE_NODE_INDEX de $CIRCLE_NODE_TOTAL"
      - slack/notify:
          event: fail
          template: basic_fail_1

  deploy:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run:
          name: Despliegue
          command: echo "Desplegando aplicación..."
      - slack/notify:
          event: pass
          custom: |
            {
              "text": "✅ ¡Hola Joe! Tu pipeline finalizó correctamente 🚀"
            }


workflows:
  version: 2
  flujo-principal:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
