version: 2.1

orbs:
  slack: circleci/slack@4.12.5

executors:
  node-executor:
    docker:
      - image: cimg/node:20.5.0

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci

  lint:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Análisis de estilo con ESLint
          command: npm run lint

  test:
    parallelism: 2
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            TEST_FILES=$(circleci tests glob "test/**/*.js" | circleci tests split --split-by=timings)
            echo "$TEST_FILES" | xargs -n 1 node
      - slack/notify:
          event: fail
          template: basic_fail_1

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Simular build
          command: echo "Construcción completa."
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2

  test_pipeline:
    jobs:
      - lint
      - test

  build_pipeline:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
